### ISSUE TITLE
D3 plots range

### ISSUE THREAD

**Issue by chartotu19** [SOCR/SOCR-Resampling-Randomization-Webapp#20]
Plots dont show well when the all values are less than 0.1. For example, plotting [0.02,0.03,0.04,0.1] will just create 1 single bar at 0.1 .

**Comment by khare-ashwini** [comment]
@chartotu19 : Can you check if the above solution works

**Comment by chartotu19** [comment]
will check it out @khare-ashwini and update the issue.

**Comment by chartotu19** [comment]
closing the issue, histogram demo looks good for the input values.
